# Generated by Django 4.2.5 on 2023-10-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='role',
            new_name='group',
        ),
    ]
