# Generated by Django 4.1.10 on 2023-11-25 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_appointment_date_appointment_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='last_name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
