# Generated by Django 4.2.5 on 2023-10-12 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_visit', models.DateField(null=True)),
                ('diagnosis', models.TextField(max_length=1000)),
                ('medication', models.TextField(max_length=600)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
